apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kubernetes.io/change-cause: kubectl set image deploy/playwright-wrapper wrapper=playwright-wrapper:1.0.1-fix-host
      --namespace=default --record=true
    meta.helm.sh/release-name: n8n
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2026-02-16T15:10:18Z"
  generation: 18
  labels:
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: playwright-wrapper
  name: playwright-wrapper
  namespace: default
  resourceVersion: "29293"
  uid: aa8b6bc2-d2e9-416e-8afd-991bfcd93498
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n
      app.kubernetes.io/name: playwright-wrapper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-17T10:45:50+01:00"
      labels:
        app.kubernetes.io/instance: n8n
        app.kubernetes.io/name: playwright-wrapper
    spec:
      containers:
      - env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: API_TOKEN
              name: playwright-wrapper-secret
        - name: TARGET_NAMESPACE
          value: default
        - name: PW_POD_LABEL_KEY
          value: app
        - name: PW_POD_LABEL_VALUE
          value: playwright-ephemeral
        - name: PW_MCP_PORT
          value: "8933"
        image: playwright-wrapper:1.0.1-fix-host
        imagePullPolicy: Never
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: wrapper
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: playwright-wrapper
      serviceAccountName: playwright-wrapper
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  conditions:
  - lastTransitionTime: "2026-02-17T09:38:12Z"
    lastUpdateTime: "2026-02-17T09:49:10Z"
    message: ReplicaSet "playwright-wrapper-79b4d57674" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-17T09:49:10Z"
    lastUpdateTime: "2026-02-17T09:49:10Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 18
  replicas: 1
  terminatingReplicas: 0
  unavailableReplicas: 1
  updatedReplicas: 1
