apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-02-17T22:29:13Z"
  labels:
    app: pw
    sid: cfa20bbf48b4d847
  name: pw-cfa20bbf48b4d847
  namespace: n8n-prod
  resourceVersion: "94504"
  uid: ff8b815f-0492-413c-a07d-ea1caf24b75d
spec:
  clusterIP: 10.96.122.230
  clusterIPs:
  - 10.96.122.230
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8933
    protocol: TCP
    targetPort: 8933
  selector:
    app: pw
    sid: cfa20bbf48b4d847
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
