---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-prod-encryption-key-secret-v2
  namespace: n8n-prod
spec:
  encryptedData:
    encryptionKey: AgCnsuJQ8a4r3pGoiPPx4crugzUEf3qdmO/DWA1eK47XbtnRYDmvWdZmPPV2gZfeK+QK6hiMgMW+g/N+5D0uYx2vFrsH5NeZhwE/9iNzSm8Ao8Qu1JL+VbM7p0HItd3reBbaY+GVSgivbHtvulmcKeQcGGfZzqERvHbMM2tNsC0OL7dZDy9PCPUAGZ92CMXNpGpLRLL7mUkP6cLyEWGE6xmg4vSq070RZP9CPf2IWw2Zjn3CIpFdL/qNinfrQ2Ms90XYuN96eAf8dO9XHwZbwdziknXr2xzlykO+2bcUJoWqvoXO335o9Q4ZP5LQekUPom72QwwyRydtCjUHXJR874OF+VqrZpdvNu2vWsc5EgK/BnjyqTDtpYSudEutahI51iyXiGLOhVO/fcF5GR3O9sSNFVzHnRgwVyjqRImfX5OqhIUwv5/giDFyfGgI23C9o9rB5J10ib7nrDlwEvNffX11NFdZLvUVDSGIzqnLoKPf614pyYglS8ZFvTx2glE343oH4DZQz+Sj8DxIbtpAOBMyDQcOEgWYoF14guna8eJ1b+2ZikKCFrCtNICSESy7/O5MVqVFjLwdlcbSH+fElDDoJAiYHkZNCgWT0lE7C/8gOxigC+cAcQFNuyQ6w68Y2YwpEH7RRRt2DvK6Jj7p3sUp1iwwsuygxRn9nISbU8k0QLfTTmVydDO7lLoBSuPBwqpNnIpHJFyQNjxK97MmhUivas5qVXQ+uw7xbUBXHsQiSyA=
  template:
    metadata:
      creationTimestamp: null
      name: n8n-prod-encryption-key-secret-v2
      namespace: n8n-prod
