---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-prod-postgresql
  namespace: n8n-prod
spec:
  encryptedData:
    password: AgBetUz/GiPCv6ZI8zzrDMNJuaex11Z3UUXi6suddR8AuhD2chfZhmmGL0n7R0ja+8cKTrU6dJMqlW/VXEBFU/8gJcYHLJHTfahYhNh9pbWxY786DR01EyaByM8t59VcrWXFsVr9lQte5gm2hmqBeRHalmgxydAq2w9yo7dS2ygY/D6kyCEL84qe1AZsvNXrjYceA0tdSkRTLpwcJ/xfhKm7l2stiI38jQeOU3qUBXredEHDFzb9s20o/rHeywLk7yi9QumOmYuerh1JxM/SB5zRa5VCPzNMlvVHGmK98JpU5XjmclPZhMOpcA8plyX89McCbDIiAQ7Cl7bn7rtppCOSq+T/JVllLIri82BEWOikPHUNEETTwH3T6ZQXAIVF/WzLX56Kny0FHPjhInLOuIwraQrXS5QyfXyiQAPegLg9WKg7+OydvAwiMyFsnruw8FI8O3NrKqJajukEmC/eAk7wCx7oTKlV13GtuP5pc+f5+2XsSoyZPG9IWiUqgD8SQsv/nv4hvbYcRnHCFGH8yfEGgmpE9VQ5AeEzmgYHOQykereU90c4pU4Gz++ZVodJy/ZPzUTBRE1udE7KY2erstBrVxz8nMMoxh9Nz4OULCnGfC/pQ7YdVf1xVC0hHjUTLV7TPDxqy0P4VCYrE9lYq+lc4tXNLULrl3DgguproZNqmPhz39krevRbi5mv837xnFkEmdl3BxXS4UBfj359gJaRf3BnJed+rw==
    postgres-password: AgARbytdt8IjyzHqjvQjzjqkGjFC5CIZyVSxuyReyltvyer6YxrwVSNy1zngvMffUzcUjtOYBqpmZvaW1Y4oQYiTKl9o/9lrHrdinfML2MbzKeMyP5NGJYcpLIvM9/c7FoX+8tSi0KIqvkj2sqGZz6zHSMNkoqGvlfmcHD5GWNhcp/OVodU7Jo8f8WsF4Ln0MryqYeaU3RGx9P5R55nReIi/8WRsRXXY3fdja36o/5bpnR/Vtw2VYQXHtmC+X+o/CoKtIx/Ca2+Kuf5RAyQJFnF0Vm+5EWtqixnQA7avlHvjHCEI3/utQ4xWvWBvVMuwH/FxGulaXw7TZgtMOGQU/nBFRnvLtxiq4U8kVL47N1ToDm1LcETziNtTnGV1w3r1VIHJ7bBFmtt5BMiGcvlOwVOaCzMu1GhP1quNn95/51d62fs4YdD+bDJw5/F/ylO7GoGOTBPBVR2IlzwHqdZRm3qeUqpzBQ3/J0+NFdAfssYqyWm4ML3AxGj4P/Fnr/eDQOnLEBDRYpWT+fUdn2Ca5utVzcdO5I32gmSXb6vqPbwjFmxhP9OjUUd5jpfKdOB2KrKQTkTpEdtlZS9Zjc8IQRwiDCAILYza/7U7yJH7QguAQvMMlIIIMdjWWGS5e6JTD3FZ5oopA0BppSi+DDrzzbS8oxAna2XaFbszYyT6Uytv2zyDfASG/AENlZjoRxXRhz4FMj+N7vnO2uR+Z/ra4F41liwfqOzwEw==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-prod-postgresql
      namespace: n8n-prod
