apiVersion: v1
kind: Secret
metadata:
  name: n8n-prod-postgresql
  namespace: n8n-prod
type: Opaque
stringData:
  password: n8n-local-password
  postgres-password: n8n-local-password
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-prod-encryption-key-secret-v2
  namespace: n8n-prod
type: Opaque
stringData:
  encryptionKey: ton-secret-tres-long-et-sur-pour-n8n
