apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "playwright-wrapper.fullname" . }}-downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # Tu peux ajuster selon tes besoins
