apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "playwright-wrapper.fullname" . }}-downloads
  labels:
    app.kubernetes.io/name: {{ include "playwright-wrapper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
