apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: n8n-prod:/Service:n8n-prod/playwright-wrapper
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"n8n-prod:/Service:n8n-prod/playwright-wrapper"},"labels":{"app.kubernetes.io/instance":"n8n-prod","app.kubernetes.io/name":"playwright-wrapper"},"name":"playwright-wrapper","namespace":"n8n-prod"},"spec":{"ports":[{"name":"http","port":8080,"targetPort":"http"}],"selector":{"app.kubernetes.io/instance":"n8n-prod","app.kubernetes.io/name":"playwright-wrapper"},"type":"ClusterIP"}}
  creationTimestamp: "2026-02-17T08:33:37Z"
  labels:
    app.kubernetes.io/instance: n8n-prod
    app.kubernetes.io/name: playwright-wrapper
  name: playwright-wrapper
  namespace: n8n-prod
  resourceVersion: "21234"
  uid: 5c9a90f3-f9dc-476d-8aeb-5276c27e148f
spec:
  clusterIP: 10.96.57.253
  clusterIPs:
  - 10.96.57.253
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: n8n-prod
    app.kubernetes.io/name: playwright-wrapper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
