apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: n8n-prod:apps/Deployment:n8n-prod/playwright-wrapper
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"n8n-prod:apps/Deployment:n8n-prod/playwright-wrapper"},"labels":{"app.kubernetes.io/instance":"n8n-prod","app.kubernetes.io/name":"playwright-wrapper"},"name":"playwright-wrapper","namespace":"n8n-prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"n8n-prod","app.kubernetes.io/name":"playwright-wrapper"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"n8n-prod","app.kubernetes.io/name":"playwright-wrapper"}},"spec":{"containers":[{"env":[{"name":"API_TOKEN","valueFrom":{"secretKeyRef":{"key":"API_TOKEN","name":"playwright-wrapper-secret"}}},{"name":"TARGET_NAMESPACE","value":"default"},{"name":"PW_POD_LABEL_KEY","value":"app"},{"name":"PW_POD_LABEL_VALUE","value":"playwright-ephemeral"},{"name":"PW_MCP_PORT","value":"8933"}],"image":"playwright-wrapper:1.0.1-fix-host","imagePullPolicy":"IfNotPresent","livenessProbe":{"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":5,"periodSeconds":20},"name":"wrapper","ports":[{"containerPort":8080,"name":"http"}],"readinessProbe":{"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":2,"periodSeconds":10},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":true,"runAsGroup":10001,"runAsNonRoot":true,"runAsUser":10001},"volumeMounts":[{"mountPath":"/tmp","name":"tmp"}]}],"securityContext":{"runAsNonRoot":true,"seccompProfile":{"type":"RuntimeDefault"}},"serviceAccountName":"playwright-wrapper","volumes":[{"emptyDir":{},"name":"tmp"}]}}}}
  creationTimestamp: "2026-02-17T08:33:37Z"
  generation: 11
  labels:
    app.kubernetes.io/instance: n8n-prod
    app.kubernetes.io/name: playwright-wrapper
  name: playwright-wrapper
  namespace: n8n-prod
  resourceVersion: "31857"
  uid: d334f2ed-7a01-415c-8ec2-a7c44968f65d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: n8n-prod
      app.kubernetes.io/name: playwright-wrapper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-02-17T11:02:47+01:00"
      labels:
        app.kubernetes.io/instance: n8n-prod
        app.kubernetes.io/name: playwright-wrapper
    spec:
      containers:
      - env:
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: API_TOKEN
              name: playwright-wrapper-secret
        - name: TARGET_NAMESPACE
          value: default
        - name: PW_POD_LABEL_KEY
          value: app
        - name: PW_POD_LABEL_VALUE
          value: playwright-ephemeral
        - name: PW_MCP_PORT
          value: "8933"
        image: docker.io/library/playwright-wrapper:1.0.1-fix-host
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: wrapper
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: playwright-wrapper
      serviceAccountName: playwright-wrapper
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
status:
  conditions:
  - lastTransitionTime: "2026-02-17T10:02:47Z"
    lastUpdateTime: "2026-02-17T10:07:40Z"
    message: ReplicaSet "playwright-wrapper-767999b448" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-02-17T10:07:42Z"
    lastUpdateTime: "2026-02-17T10:07:42Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 11
  replicas: 1
  terminatingReplicas: 0
  unavailableReplicas: 1
  updatedReplicas: 1
