apiVersion: apps/v1
kind: Deployment
metadata:
  name: browserless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: browserless
  template:
    metadata:
      labels:
        app: browserless
    spec:
      containers:
        - name: browserless
          image: browserless/chrome:latest
          ports:
            - containerPort: 3000
          env:
            - name: MAX_CONCURRENT_SESSIONS
              value: "10"
            - name: TOKEN
              value: "votre_token_optionnel"
