apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-17T20:17:15Z"
    generation: 1
    labels:
      app: pw
      sid: 32e67cc9308e113f
    name: pw-32e67cc9308e113f
    namespace: n8n-prod
    resourceVersion: "81376"
    uid: 79e956d6-eec6-4192-9cb9-b9244b298d07
  spec:
    containers:
    - args:
      - cli.js
      - --headless
      - --browser
      - chromium
      - --no-sandbox
      - --allowed-hosts
      - '*'
      - --host
      - 0.0.0.0
      - --port
      - "8933"
      - --shared-browser-context
      command:
      - node
      image: mcr.microsoft.com/playwright/mcp:latest
      imagePullPolicy: IfNotPresent
      name: playwright
      ports:
      - containerPort: 8933
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-mbmw9
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: pw-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-mbmw9
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:17:16Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:17:15Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:17:16Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:17:16Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:17:15Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://b9e2fc818b2d79d49d82859d6aea6d3eed3e6182743431c8c0a06e4e09d4f65b
      image: mcr.microsoft.com/playwright/mcp:latest
      imageID: mcr.microsoft.com/playwright/mcp@sha256:a9d607e571d70954acc36de7a45e7f424a94cebdfba973b1f404435108c60f3f
      lastState: {}
      name: playwright
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-17T20:17:15Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-mbmw9
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.19.0.3
    hostIPs:
    - ip: 172.19.0.3
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.243
    podIPs:
    - ip: 10.244.0.243
    qosClass: BestEffort
    startTime: "2026-02-17T20:17:15Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-17T20:24:53Z"
    generation: 1
    labels:
      app: pw
      sid: 481624059c376af7
    name: pw-481624059c376af7
    namespace: n8n-prod
    resourceVersion: "82169"
    uid: 8c7c5a26-fb56-41c3-9a86-5222a49a91f7
  spec:
    containers:
    - args:
      - cli.js
      - --headless
      - --browser
      - chromium
      - --no-sandbox
      - --allowed-hosts
      - '*'
      - --host
      - 0.0.0.0
      - --port
      - "8933"
      - --shared-browser-context
      command:
      - node
      image: mcr.microsoft.com/playwright/mcp:latest
      imagePullPolicy: IfNotPresent
      name: playwright
      ports:
      - containerPort: 8933
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-z85h2
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: pw-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-z85h2
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:24:54Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:24:53Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:24:54Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:24:54Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:24:53Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://88cc019473cf1a3f7bcb01ae9528af953e1eaddab9f9854a8e5ffdf23c8fd0ee
      image: mcr.microsoft.com/playwright/mcp:latest
      imageID: mcr.microsoft.com/playwright/mcp@sha256:a9d607e571d70954acc36de7a45e7f424a94cebdfba973b1f404435108c60f3f
      lastState: {}
      name: playwright
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-17T20:24:53Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-z85h2
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.19.0.3
    hostIPs:
    - ip: 172.19.0.3
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.248
    podIPs:
    - ip: 10.244.0.248
    qosClass: BestEffort
    startTime: "2026-02-17T20:24:53Z"
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: "2026-02-17T20:07:07Z"
    generation: 1
    labels:
      app: pw
      sid: f32f5dbdd9570c9d
    name: pw-f32f5dbdd9570c9d
    namespace: n8n-prod
    resourceVersion: "80341"
    uid: 4c336fe5-fee1-4874-8796-7d5d2ac2e83e
  spec:
    containers:
    - args:
      - cli.js
      - --headless
      - --browser
      - chromium
      - --no-sandbox
      - --allowed-hosts
      - '*'
      - --host
      - 0.0.0.0
      - --port
      - "8933"
      - --shared-browser-context
      command:
      - node
      image: mcr.microsoft.com/playwright/mcp:latest
      imagePullPolicy: IfNotPresent
      name: playwright
      ports:
      - containerPort: 8933
        protocol: TCP
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: false
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-727tj
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: pw-control-plane
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Never
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-727tj
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:07:08Z"
      observedGeneration: 1
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:07:07Z"
      observedGeneration: 1
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:07:08Z"
      observedGeneration: 1
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:07:08Z"
      observedGeneration: 1
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2026-02-17T20:07:07Z"
      observedGeneration: 1
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://5a949b7ec587b7067393ec34e327bc240f8cd57489a85086b694d7409f1fa5a6
      image: mcr.microsoft.com/playwright/mcp:latest
      imageID: mcr.microsoft.com/playwright/mcp@sha256:a9d607e571d70954acc36de7a45e7f424a94cebdfba973b1f404435108c60f3f
      lastState: {}
      name: playwright
      ready: true
      resources: {}
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2026-02-17T20:07:07Z"
      user:
        linux:
          gid: 1000
          supplementalGroups:
          - 1000
          uid: 1000
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-727tj
        readOnly: true
        recursiveReadOnly: Disabled
    hostIP: 172.19.0.3
    hostIPs:
    - ip: 172.19.0.3
    observedGeneration: 1
    phase: Running
    podIP: 10.244.0.237
    podIPs:
    - ip: 10.244.0.237
    qosClass: BestEffort
    startTime: "2026-02-17T20:07:07Z"
kind: List
metadata:
  resourceVersion: ""
